server:
  port: 9000
  servlet:
    context-path: /productos
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://${hostdb}:3306/pedidos?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
eureka:
  cliente:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${hosteureka}:8761/eureka 
    instance:
      hostname: ${hostreal}
